IMAGES_FOR_TRAIN_PATH = "friends_images/"
IMAGES_FOR_TEST_PATH = "generated_collages/"

TRAINING_DATA_FILE_NAME = "trainner.yml"
NAMES_OF_PEOPLE_FILE_NAME = "names_with_ids.json"
PROJECT_DICT_PATH = "C:/Users/kacpe/Visual Studio Projects/face_recognition"

CAM_WIDTH = 640
CAM_HEIGHT = 480

RUN_CAMERA = True

UP_CONFIDENCE = 80
DOWN_CONFIDENCE = 20

DISPLAY_FRAME = True
FRAME_COLOR = (0, 255, 0)
FRAME_WIDTH = 2 

FONT_SIZE = 0.8
FONT_COLOR = (0, 255, 0)

INFO_RECTANGLE_POSITION = (0, 0)
INFO_RECTANGLE_SIZE = (400, 200)
INFO_RECTANGLE_COLOR = (0, 0, 0)